Campos de cidade e estado alterados para ModelChoiceField, alterações no html e script para atualizar BD.
regiov/voluntarios pull request #48
Opened 2023-05-23 21:36 UTC by Diogojlq

Olá @regiov , acredito que esteja pronto, qualquer coisa me retorna e eu conserto.

2023-05-24 04:47 UTC, Diogojlq commented
Vou criar alguns comentários e limpar algumas coisas no código.

2023-05-31 12:33 UTC, regiov requested changes
Olá @Diogojlq, desculpe a demora - finalmente consegui revisar seu pull request. Fiz vários comentários sugerindo pequenas alterações, mas de maneira geral o conjunto todo está muito bom e coerente. Só dois pontos que queria acrescentar aqui: 1) Como essa nova estrutura de estado/cidade é fundamental para o correto funcionamento do site, é importante alterar o readme para mencionar aos novos desenvolvedores que é preciso rodar aquele linha de comando antes de usar o site. 2) O novo esquema de estado/cidade também deverá ser usado no formulário de entidades. Não sei se você esqueceu ou se prefere deixar para um pull request separado depois.
Abs!

2023-05-31 12:33 UTC, regiov commented on vol/forms.py
> +        return self.cleaned_data['estado']
Se for para só deixar o retorno do valor em cleaned_data, melhor remover o método, com a ressalva que se alguém quiser submeter o form programaticamente com um estado incorreto, acho que vai gravar no banco. Quer experimentar?

2023-05-31 12:33 UTC, regiov commented on vol/models.py
> +    uf = models.CharField(max_length=50)
Não deveria ser um CharField com max_length=2, igual você colocou no modelo Voluntario?

2023-05-31 12:33 UTC, regiov commented on vol/templates/vol/formulario_voluntario.html
> +                                  },
Tem certeza que isso é necessário? As chamadas serão sempre do tipo "GET" para o mesmo domínio...

2023-05-31 12:33 UTC, regiov commented on vol/management/commands/atualiza_municipios.py
> +                    dados_atuais = Cidade.objects.all()
Se essa variável não estiver sendo usada, melhor remover a linha.

2023-05-31 12:33 UTC, regiov commented on vol/management/commands/atualiza_municipios.py
> +            UFs = ["RO","AC","AM","RR","PA","AP","MA","PI","CE","RN","PB","PE","AL","SE","BA","MG","ES","RJ","SP","PR","SC","RS","MS","MT","GO","DF"]
Como você fez para preencher a tabela estado? Manualmente? Acho que antes de atualizar a tabela cidade, você poderia verificar se a tabela estado está vazia. Se estiver, use o dicionário que removeu do models.py, que tinha todas as siglas e nomes de estado, coloque ele aqui nesse programa, para preencher a tabela estado, e só depois atualize as cidades.

2023-05-31 12:33 UTC, regiov commented on vol/models.py
> +
Estava tentando entender porque você voltou, e lembrei que o formulário de entidade também envolve cidade e estado. Enquanto não alterarmos também o formulário de entidades esse código deve mesmo ser mantido...

2023-05-31 13:59 UTC, Diogojlq commented on website/settings.py
> +GEOS_LIBRARY_PATH = r'C:\Program Files\PostgreSQL\15\bin\libgeos_c.dll'
Esse arquivo foi confusão minha com o git, já vou corrigir essas coisas e fazer os commits corretos.

2023-05-31 15:02 UTC, Diogojlq commented on vol/forms.py
> +        return self.cleaned_data['cidade']
Pelo que eu li em algumas fontes, se o formulário for um ModelForm, o Django já válida os dados automaticamente, mas não sei como seria nesse caso específico de alguém tentar ativamente burlar o sistema. Se for mesmo necessário, qual seria solução mais interessante ? Criar os relacionamentos no banco ou criar uma validação ?

2023-05-31 15:18 UTC, regiov commented on vol/forms.py
> +    cidade = forms.ModelChoiceField(label=u'Cidade em que reside',queryset=Cidade.objects.all())
Tem certeza, @Diogojlq? Porque se o django usa esse queryset em algum outro lugar do código pra validar os dados, então nem precisaria do clean_estado...(?) Achei que esse queryset servisse apenas para prover o conteúdo inicial. Seria legal fazer um teste. Tente submeter um estado XX pra ver se valida só tendo o queryset.

2023-05-31 21:20 UTC, Diogojlq commented on vol/forms.py
> +    cidade = forms.ModelChoiceField(label=u'Cidade em que reside',queryset=Cidade.objects.all())
Testei alterando o nome do estado para XX no inspecionar, e funcionou, só não tenho certeza se era isso que deveria ser feito. As opções criadas no HTML tem um valor que é o ID do estado no banco, e este valor que é selecionado pelo Django, alterei também o valor, se ele for inexistente, não é possível selecionar uma cidade e enviar o formulário, e se trocar o valor, ele mostra as cidades filtradas por aquele valor, independente do que esteja escrito no dropdown, então os registros estarão sempre corretos, eu acho...

2023-05-31 21:27 UTC, Diogojlq commented on vol/forms.py
> +        return self.cleaned_data['cidade']
Perfeito ! Vou fazer isso.

2023-05-31 21:39 UTC, Diogojlq commented on vol/management/commands/atualiza_municipios.py
> +            UFs = ["RO","AC","AM","RR","PA","AP","MA","PI","CE","RN","PB","PE","AL","SE","BA","MG","ES","RJ","SP","PR","SC","RS","MS","MT","GO","DF"]
Preenchi utilizando a API do IBGE, mas apaguei o código porque não pensei nesse fator. Vou atualizar o cadastro de entidades e mover o dicionário para esse arquivo, acredito que ficará melhor que deixar ele no arquivo que está, onde já não será mias utilizado, certo ?

2023-05-31 21:44 UTC, Diogojlq commented on vol/forms.py
> +    cidade = forms.ModelChoiceField(label=u'Cidade em que reside',queryset=Cidade.objects.all())
Eu pensei que seria interessante remover o clean_estado, assim como o clean_cidade, pois acredito que não precise mesmo dessa validação, mas gostaria de saber o que acha.

2023-05-31 22:58 UTC, regiov commented on vol/management/commands/atualiza_municipios.py
> +            UFs = ["RO","AC","AM","RR","PA","AP","MA","PI","CE","RN","PB","PE","AL","SE","BA","MG","ES","RJ","SP","PR","SC","RS","MS","MT","GO","DF"]
Sim, se você fizer as mesmas alterações no cadastro de entidades, creio que não seja mais necessário ter aquelas siglas de estado no models.py, mas seria bom ver se não tem mais nada usando isso no código (algum formulário de busca, por exemplo).

2023-06-01 15:07 UTC, regiov commented on vol/forms.py
> +    cidade = forms.ModelChoiceField(label=u'Cidade em que reside',queryset=Cidade.objects.all())
Tudo bem, qualquer coisa eu faço alguns testes aqui depois de incorporar o pull request. Se for necessário voltar algum código ou alterar alguma coisa eu faço isso sem problema. Fique tranquilo.

2023-06-01 15:45 UTC, Diogojlq commented on vol/management/commands/atualiza_municipios.py
> +            UFs = ["RO","AC","AM","RR","PA","AP","MA","PI","CE","RN","PB","PE","AL","SE","BA","MG","ES","RJ","SP","PR","SC","RS","MS","MT","GO","DF"]
Estou alterando o cadastro de entidades, e no formulário existem os campos de bairro e logradouro, devo mantê-los como estão ? Alguém poderia registrar um CEP errado por exemplo, mesmo com a cidade e estado estando corretos.

2023-06-02 16:35 UTC, Diogojlq commented on vol/management/commands/atualiza_municipios.py
> +            UFs = ["RO","AC","AM","RR","PA","AP","MA","PI","CE","RN","PB","PE","AL","SE","BA","MG","ES","RJ","SP","PR","SC","RS","MS","MT","GO","DF"]
Apenas alterei os campos de estado e cidade, mantendo os demais campos como estavam.

2023-06-02 21:57 UTC, Diogojlq commented on vol/templates/vol/formulario_voluntario.html
> +                                  },
Removido.

2023-06-22 20:50 UTC, Diogojlq commented
Boa noite @regiov. Fiz esse commit na mesma branch por engano, estou entendendo como corrigir e logo envio um novo pull request com o código para a funcionalidade de favoritar entidades.

2023-06-23 01:09 UTC, regiov commented
Legal, @Diogojlq, eu ia comentar isso mesmo. Penso que o ideal seja, a cada nova funcionalidade que você for implementar, criar um novo branch no seu repositório, trabalhar nele, e quando terminar fazer o pull request a partir dele. Depois que eles forem incorporados aqui pelo repositório principal, você volta para o o seu master/main, atualiza ele, e assim por diante. Por sinal, pretendo sem falta incorporar suas alterações das cidades/estados nesse fim de semana. É que tá bem corrido por aqui ultimamente.

2023-06-28 22:43 UTC, Diogojlq commented
Boa noite @regiov , finalmente consegui entender a coisa toda, fiz um git reset na new_branch, mas antes movi as alterações responsáveis pela funcionalidade de favoritar entidades para uma nova branch, então fiz o um git push -f, apagando o commit que deveria ter feito na outra branch.
Cheguei em um ponto onde acredito ser uma questão de preferência, pois não parece haver um padrão de como fazer isso :
Devo abrir o PR com as alterações para a funcionalidade de favoritar entidades a partir de uma branch que já contém o código da "new_branch", ou "criar" essas alterações em uma nova branch que foi criada a partir da master, que não contém as alterações da "new_branch" ?

2023-06-29 12:47 UTC, regiov commented
@Diogojlq, quando a segunda issue tem muita intersecção com a issue anterior (ou seja, alterações nas mesmas áreas de código), acho que eu criaria um branch a partir do branch da issue anterior. Do contrário, criaria um branch a partir do master mesmo. Repare que muito disso nem precisaríamos estar nos preocupando se eu tivesse conseguido revisar o primeiro pull request com mais celeridade, mas talvez seja interessante acontecer por aprendizado mesmo. Já fiz pull requests em outros projetos que levaram vários meses para serem analisados. Enfim, coincidentemente acho que hoje de manhã consigo rever novamente o primeiro pull request.

2023-06-29 13:07 UTC, merged